### ISSUE TITLE
Any GUI?

### ISSUE THREAD

**Issue by yesbhautik** [virtuosoft-dev/hestiacp-pluginable#3]

**Comment by Steveorevo** [comment]
The only "GUI" is under HestiaCP's Configuration -> Plugins section. Plugins built to work with HestiaCP-Pluginable appear there and furnish the option to Yes (enable), No (disable), or Uninstall to remove the plugin. 

HestiaCP-Pluginable is merely a (soon-to-be) documented API for plugins to extend HestiaCP's abilities. See the readme for plugins that use this repo.
